### ISSUE TITLE
No respond when I play DRM video

### ISSUE THREAD

**Issue by CHDWEB** [Avalonswanderer/wideXtractor#1]
Hello:
     May I ask how to fix this issue?  The script doesn't respond anything when I play DRM video

> PS C:\Users\xxxx\frida\wideXtractor-main> python wideXtractor.py new
[+] Attached to mediadrmserver
[+] Searching Widevine Module in mediadrmserver.
[+] Widevine Module libmediadrm.so found.
[+] Processing Frida JS scripts
        [+] Loading hooks
        [+] Hooks loaded successfully
[+] Listening...

> 

Thank you so much
![test](https://user-images.githubusercontent.com/92210393/159248418-ba3e7d13-d98f-4661-abb0-1bd4b457ce37.png)

**Comment by Avalonswanderer** [comment]
Hello,

It may be a problem related to the symbols within your lbmediadrm.so, if no
_oeccXX functions can be found, try to change the code to remove
libmediadrm of the list to search for another widevine lib.

**Comment by 89z** [comment]
Same problem here
