### ISSUE TITLE
L1 cdm or L3 cdm or the content key?

### ISSUE THREAD

**Issue by Hackermanswitch** [Avalonswanderer/wideXtractor#2]
hi i was wondering does this provide the CDM and if so does it work on L1 aswell on L3? or does this dump the key of the specific media file that was played?

**Comment by Avalonswanderer** [comment]
This will work for L1 and L3 to inspect messages related to the CDM. However the content keys and any encrypted data can only be retrieved if the certificate private key / root of trust have been previously dump. You can go to https://github.com/Avalonswanderer/widevine_key_ladder for using keys to mimic the key ladder.
